#!/bin/bash

# Quick Re-import Helper Script
echo "================================================"
echo "🔄 n8n Workflow Re-import Helper"
echo "================================================"
echo ""
echo "⚠️  CRITICAL: You must re-import all 4 workflows manually!"
echo ""
echo "📋 Steps to follow:"
echo ""
echo "1️⃣  Open n8n in your browser:"
echo "    👉 http://localhost:5678"
echo ""
echo "2️⃣  For EACH of the 4 workflows, do the following:"
echo ""
echo "    a) Click on the workflow name (top-left)"
echo "    b) Click the '...' menu → Delete workflow"
echo "    c) Confirm deletion"
echo ""
echo "3️⃣  Import the updated workflows:"
echo ""
echo "    a) Click 'Workflows' in sidebar"
echo "    b) Click '+ Add workflow' → 'Import from File'"
echo "    c) Select file from workflows/hackathon/"
echo "    d) Click 'Import'"
echo "    e) ACTIVATE the workflow (toggle switch top-right)"
echo ""
echo "📁 Files to import (IN ORDER):"
echo ""
echo "    ✅ 1-collector-workflow.json"
echo "    ✅ 2-validator-workflow.json"
echo "    ✅ 3-processor-workflow.json"
echo "    ✅ 4-reporter-workflow.json"
echo ""
echo "================================================"
echo ""
echo "🔍 After re-import, verify in n8n editor that each workflow has:"
echo ""
echo "   • A new 'Prepare Log Data' Code node"
echo "   • Connected between main node and 'Log to PostgreSQL'"
echo ""
echo "================================================"
echo ""
echo "🧪 Then test the pipeline:"
echo ""
echo "   curl -X POST http://localhost:5678/webhook/collect-data \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"location\": \"Tokyo\", \"country\": \"jp\"}'"
echo ""
echo "================================================"
echo ""
echo "✅ Verify logs with:"
echo ""
echo "   docker exec -it n8n-postgres psql -U n8n -d n8n -c \\"
echo "     \"SELECT execution_id, stage, status FROM audit_logs ORDER BY timestamp DESC LIMIT 20;\""
echo ""
echo "   You should see rows from all 4 stages:"
echo "   - collection"
echo "   - validation"
echo "   - processing"
echo "   - reporting"
echo ""
echo "================================================"
echo ""
read -p "Press ENTER to open n8n in browser (or Ctrl+C to exit)..."
open http://localhost:5678 2>/dev/null || echo "Please manually open: http://localhost:5678"
