apiVersion: 1

datasources:
  - name: PostgreSQL-n8n
    type: postgres
    access: proxy
    url: postgres:5432
    database: n8n
    user: n8n
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      maxOpenConns: 10
      maxIdleConns: 5
      maxConnLifetimeSeconds: 300
    isDefault: true
    editable: true

  - name: PostgreSQL-System
    type: postgres
    access: proxy
    url: postgres:5432
    database: postgres
    user: n8n
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: true

  - name: n8n-Metrics-API
    type: prometheus
    access: proxy
    url: http://n8n:5678/metrics
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "30s"
      httpMethod: GET