global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'n8n-orchestrator'
    replica: 'prometheus-01'

rule_files:
  - "alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # n8n metrics
  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n:5678']
    scrape_interval: 30s
    metrics_path: /metrics
    basic_auth:
      username: 'admin'
      password: 'admin_password'

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    params:
      format: [prometheus]

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics
    basic_auth:
      username: 'admin'
      password: 'admin_password'

  # Nginx metrics (if nginx-prometheus-exporter is enabled)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: /metrics

  # Custom webhook for n8n workflow metrics
  - job_name: 'n8n-workflows'
    static_configs:
      - targets: ['n8n:5678']
    scrape_interval: 60s
    metrics_path: /webhook/metrics
    scheme: http